changes after applying at work

diff --git a/run_once_install-packages.sh.tmpl b/run_once_install-packages.sh.tmpl
--- a/run_once_install-packages.sh.tmpl
+++ b/run_once_install-packages.sh.tmpl
@@ -67,6 +67,30 @@ else
     echo "Homebrew already installed."
 fi
 
+# Install yazi and dependencies
+packages=(
+  yazi
+  # ffmpeg # (for video thumbnails)
+  sevenzip # (for archive extraction and preview)
+  jq # (for JSON preview)
+  poppler # (for PDF preview) [!huge amount of dependencies!]
+  fd # (for file searching)
+  # ripgrep # (for file content searching)
+  # fzf # (for quick file subtree navigation)
+  # zoxide # (for historical directories navigation, requires fzf)
+  resvg # (for SVG preview)
+  imagemagick # (for Font, HEIC, and JPEG XL preview)
+)
+
+for pkg in "${packages[@]}"; do
+  if ! brew list --formula --versions "$pkg" &>/dev/null; then
+    echo "Installing $pkg..."
+    brew install "$pkg" || die "Could not install $pkg."
+  else
+    echo "$pkg already installed."
+  fi
+done
+
 # Install VS Code
 if ! command -v code &>/dev/null; then
     echo "Installing VS Code..."
@@ -88,7 +112,8 @@ if ! command -v google-chrome &>/dev/null; then
     echo "Installing Google Chrome..."
     TMP_FILE=$(mktemp)
     curl -L https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -o "$TMP_FILE"
-    sudo apt install -y "$TMP_FILE" || die "Could not install Google Chrome."
+    sudo dpkg -i "$TMP_FILE"
+    sudo apt -f install -y || die "Could not fix dependencies for Google Chrome."
     rm -f "$TMP_FILE"
 else
     echo "Google Chrome already installed."
