whitespaces and starship

diff --git a/run_once_install-packages.sh.tmpl b/run_once_install-packages.sh.tmpl
--- a/run_once_install-packages.sh.tmpl
+++ b/run_once_install-packages.sh.tmpl
@@ -39,6 +39,7 @@ sudo apt-get install -y \
     ffmpeg \
     firefox \
     fzf \
+    gimp \
     git \
     git-lfs \
     gnome-tweaks \
@@ -69,26 +70,26 @@ fi
 
 # Install yazi and dependencies
 packages=(
-  yazi
-  # ffmpeg # (for video thumbnails)
-  sevenzip # (for archive extraction and preview)
-  jq # (for JSON preview)
-  poppler # (for PDF preview) [!huge amount of dependencies!]
-  fd # (for file searching)
-  # ripgrep # (for file content searching)
-  # fzf # (for quick file subtree navigation)
-  # zoxide # (for historical directories navigation, requires fzf)
-  resvg # (for SVG preview)
-  imagemagick # (for Font, HEIC, and JPEG XL preview)
+    yazi
+    # ffmpeg # (for video thumbnails)
+    sevenzip # (for archive extraction and preview)
+    jq       # (for JSON preview)
+    poppler  # (for PDF preview) [!huge amount of dependencies!]
+    fd       # (for file searching)
+    # ripgrep # (for file content searching)
+    # fzf # (for quick file subtree navigation)
+    # zoxide # (for historical directories navigation, requires fzf)
+    resvg       # (for SVG preview)
+    imagemagick # (for Font, HEIC, and JPEG XL preview)
 )
 
 for pkg in "${packages[@]}"; do
-  if ! brew list --formula --versions "$pkg" &>/dev/null; then
-    echo "Installing $pkg..."
-    brew install "$pkg" || die "Could not install $pkg."
-  else
-    echo "$pkg already installed."
-  fi
+    if ! brew list --formula --versions "$pkg" &>/dev/null; then
+        echo "Installing $pkg..."
+        brew install "$pkg" || die "Could not install $pkg."
+    else
+        echo "$pkg already installed."
+    fi
 done
 
 # Install VS Code
